### User Create Test
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "password": "123",
  "password_confirmation": "123",
  "title": "test title",
  "admin": true
}

### User Login add JWT in response message to variable below
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "123"
}

### JWT Variables
@jwt = 
@jwt_admin = 

### Department Create Test
POST http://localhost:3000/departments.json
Content-Type: application/json

{
  "depart_name": "test sdfname",
  "manager_id": 1
}

### Department Update Test
PATCH http://localhost:3000/departments/5.json
Content-Type: application/json

{
  "user_id": 1, 
  "depart_name": "test name",
  "manager_id": 10
}

### Department Delete Test
DELETE http://localhost:3000/departments/5.json
Authorization: Bearer {{jwt_admin}}